### ISSUE TITLE
Labeling of the X-axis for charts too low [Marmota 22.35.1]

### ISSUE THREAD

**Issue by McPringle** [marmota-app/feedback#10]
The following Markdown:
```markdown
{design=marmota.app/dark}

#{shadow=true} Chart Test
| Version | JEPs |{chart;type=bar}
| ------- | ---- |
|       A |   50 |
|       B |   91 |

```

produces the following output:
![image](https://user-images.githubusercontent.com/1254039/193243000-2a599579-ebe5-420a-bd0f-3a0f90e3ea32.png)

The "A" is shown correctly below the bar, the "B" is way too low and outside the visible area. If I remove the slide title, the "B" will be visible:
![image](https://user-images.githubusercontent.com/1254039/193243691-268ca829-e1f0-4046-b5ff-fc5ce138670b.png)

This effect is visible in the preview and in the presentation. I would like to use the chart together with a slide title.

It happens to every second bar:
![image](https://user-images.githubusercontent.com/1254039/193244621-2f9deae2-a26d-4088-894f-2986accb86dc.png)

**Comment by dtanzer** [comment]
This is a known issue:

Every second label is rendered in the next line (on purpose) to support longer texts for labels. The chart does not yet know that the label would have enough room in the same line. Even if the labels were rendered on a single line, that chart would not fit that particular slide.

Since the chart cannot know that it is too big for the current slide, use "size options" to make it smaller (https://marmota.app/docs/editing/options/size/). Your chart probably fits the slide with "width=70" or so.

**Comment by McPringle** [comment]
I didn't know that option, I should have taken a look at the website. Thanks, it works for diagrams!
